import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import type { CommandRunner } from "./ports.ts";
import type { AuditRow, AuditState, GitProvenance } from "./types.ts";
import { summarize } from "./validation.ts";

export const RAW_TSV_CHUNK_BYTES = 48_000;
const SAFE_GITHUB_COMMENT_BYTES = 60_000;

function githubRefUrl(repositoryUrl: string, kind: "tree" | "commit", ref: string): string {
	return `${repositoryUrl}/${kind}/${encodeURIComponent(ref)}`;
}

function markdownCell(value: string): string {
	return value.replace(/\|/g, "\\|").replace(/[\r\n]+/g, " ").trim() || "—";
}

export function rawAuditMarker(provenance: GitProvenance, task: string, part: number): string {
	return `<!-- pi-audit-trail:${provenance.repository}:${task}:part:${part} -->`;
}

export function splitRawTsv(rawTsv: string, maxBytes = RAW_TSV_CHUNK_BYTES): string[] {
	if (!rawTsv.endsWith("\n")) {
		throw new Error("Canonical audit TSV must end with a newline before it can be published exactly");
	}
	const lines = rawTsv.match(/.*\n/g) ?? [];
	const chunks: string[] = [];
	let chunk = "";
	let chunkBytes = 0;
	for (const line of lines) {
		const lineBytes = Buffer.byteLength(line, "utf8");
		if (lineBytes > maxBytes) {
			throw new Error(`Audit TSV contains a row larger than the ${maxBytes}-byte publication chunk limit`);
		}
		if (chunk && chunkBytes + lineBytes > maxBytes) {
			chunks.push(chunk);
			chunk = "";
			chunkBytes = 0;
		}
		chunk += line;
		chunkBytes += lineBytes;
	}
	if (chunk) chunks.push(chunk);
	return chunks.length ? chunks : [rawTsv];
}

export function tsvFence(rawTsv: string): string {
	const longest = Math.max(0, ...Array.from(rawTsv.matchAll(/`+/g), (match) => match[0].length));
	return "`".repeat(Math.max(3, longest + 1));
}

export function buildRawGitHubComments(state: AuditState, rows: AuditRow[], rawTsv: string): string[] {
	if (!state.provenance) throw new Error("This audit has no Git provenance; start a new audit with this version.");
	const provenance = state.provenance;
	const chunks = splitRawTsv(rawTsv);
	const fence = tsvFence(rawTsv);
	const stats = summarize(rows);
	const branchLink = githubRefUrl(provenance.repositoryUrl, "tree", provenance.branch);
	const commitLink = githubRefUrl(provenance.repositoryUrl, "commit", provenance.startCommit);

	return chunks.map((chunk, index) => {
		const part = index + 1;
		const lines = [
			rawAuditMarker(provenance, state.task, part),
			`## Decision audit: \`${state.task}\`${chunks.length > 1 ? ` (${part}/${chunks.length})` : ""}`,
			"",
		];
		if (index === 0) {
			lines.push(
				"This is the canonical, append-only audit source for automated or human review.",
				"",
				"- **Format:** UTF-8 TSV with a header row; one decision per subsequent row.",
				"- **History:** Rows remain in the file; `supersedes` identifies a decision replaced by a later row.",
				"- **State:** `result` records verification state and `confidence` records decision confidence.",
				`- **Decisions:** ${stats.total} total · ${stats.active} active`,
				"",
				"### Provenance",
				"",
				`[${provenance.repository}](${provenance.repositoryUrl}) · original branch [\`${markdownCell(provenance.branch)}\`](${branchLink}) · starting commit [\`${provenance.startCommit.slice(0, 12)}\`](${commitLink}) · worktree ${provenance.worktreeDirty ? "dirty" : "clean"} · Pi session \`${markdownCell(provenance.sessionId)}\``,
				"",
			);
		} else {
			lines.push("Continuation of part 1. Concatenate TSV blocks in part order to recover the exact file.", "");
		}
		lines.push(
			"<details>",
			`<summary>Raw audit TSV${chunks.length > 1 ? ` — part ${part} of ${chunks.length}` : ""}</summary>`,
			"",
			`${fence}tsv\n${chunk}${fence}`,
			"</details>",
			"",
			"---",
			"_Generated by [pi-audit-trail](https://github.com/0xLaurenzo/audit-trail).  The fenced block is unmodified source data._",
			"",
		);
		const body = lines.join("\n");
		if (Buffer.byteLength(body, "utf8") > SAFE_GITHUB_COMMENT_BYTES) {
			throw new Error(`Generated audit comment part ${part} exceeds the safe GitHub comment limit`);
		}
		return body;
	});
}

interface PullRequest {
	number: number;
	url: string;
	title: string;
	headRefName: string;
	baseRefName: string;
}

interface GitHubComment {
	id: number;
	html_url: string;
	body: string;
	user?: { login?: string };
}

export interface PublishAuditInput {
	runner: CommandRunner;
	state: AuditState;
	rows: AuditRow[];
	rawTsv: string;
	selector: string;
}

export interface PublishAuditResult {
	prNumber: number;
	prUrl: string;
	commentUrl: string;
	commentCount: number;
}

export async function publishRawAudit(input: PublishAuditInput): Promise<PublishAuditResult> {
	const provenance = input.state.provenance;
	if (!provenance) throw new Error("This audit has no Git provenance; start a new audit with this version.");
	const prResult = await input.runner.exec(
		"gh",
		["pr", "view", input.selector, "--repo", provenance.repository, "--json", "number,url,title,headRefName,baseRefName"],
		{ timeout: 30_000 },
	);
	if (prResult.code !== 0) throw new Error(prResult.stderr.trim() || "could not resolve pull request");
	const pr = JSON.parse(prResult.stdout) as PullRequest;
	if (provenance.branch !== "DETACHED" && pr.headRefName !== provenance.branch) {
		throw new Error(`PR #${pr.number} belongs to ${pr.headRefName}, but this audit started on ${provenance.branch}`);
	}

	const bodies = buildRawGitHubComments(input.state, input.rows, input.rawTsv);
	const markerPrefix = `<!-- pi-audit-trail:${provenance.repository}:${input.state.task}:part:`;
	const userResult = await input.runner.exec("gh", ["api", "user", "--jq", ".login"], { timeout: 30_000 });
	if (userResult.code !== 0) throw new Error(userResult.stderr.trim() || "GitHub authentication failed");
	const login = userResult.stdout.trim();
	const commentsResult = await input.runner.exec(
		"gh",
		["api", "--paginate", "--slurp", `repos/${provenance.repository}/issues/${pr.number}/comments?per_page=100`],
		{ timeout: 30_000 },
	);
	if (commentsResult.code !== 0) {
		throw new Error(commentsResult.stderr.trim() || "could not list pull-request comments");
	}
	const comments = (JSON.parse(commentsResult.stdout) as GitHubComment[][]).flat();
	const managed = comments.filter(
		(comment) => comment.user?.login === login && comment.body.includes(markerPrefix),
	);
	const unused = new Map(managed.map((comment) => [comment.id, comment]));
	const tempDir = await mkdtemp(join(tmpdir(), "audit-trail-publish-"));
	const bodyPath = join(tempDir, "comment.json");
	let publishedUrl = pr.url;
	try {
		for (const [index, body] of bodies.entries()) {
			const marker = rawAuditMarker(provenance, input.state.task, index + 1);
			const existing = managed.find((comment) => comment.body.includes(marker));
			if (existing) unused.delete(existing.id);
			await writeFile(bodyPath, JSON.stringify({ body }), { encoding: "utf8", mode: 0o600 });
			const endpoint = existing
				? `repos/${provenance.repository}/issues/comments/${existing.id}`
				: `repos/${provenance.repository}/issues/${pr.number}/comments`;
			const publishResult = await input.runner.exec(
				"gh",
				["api", "--method", existing ? "PATCH" : "POST", endpoint, "--input", bodyPath],
				{ timeout: 30_000 },
			);
			if (publishResult.code !== 0) {
				throw new Error(publishResult.stderr.trim() || `could not publish audit TSV part ${index + 1}`);
			}
			const published = JSON.parse(publishResult.stdout) as { html_url?: string };
			if (index === 0 && published.html_url) publishedUrl = published.html_url;
		}
		for (const stale of unused.values()) {
			const deleteResult = await input.runner.exec(
				"gh",
				["api", "--method", "DELETE", `repos/${provenance.repository}/issues/comments/${stale.id}`],
				{ timeout: 30_000 },
			);
			if (deleteResult.code !== 0) {
				throw new Error(deleteResult.stderr.trim() || `could not remove stale audit comment ${stale.id}`);
			}
		}
	} finally {
		await rm(tempDir, { recursive: true, force: true });
	}
	return {
		prNumber: pr.number,
		prUrl: pr.url,
		commentUrl: publishedUrl,
		commentCount: bodies.length,
	};
}
